name: firebase_video_upload
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #firebase
  firebase_storage: ^8.0.0
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.2

  #image picker
  image_picker: ^0.7.3

  #video controllers
  video_player: ^2.0.2
  # minSdk version to at least 24
  flutter_ffmpeg: ^0.4.0
  chewie: ^1.0.0

  #path provider
  path_provider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

